siteTitle="Mali"
baseColor = "#3CBCBC"
docPages = [
  "/docs/",
  "/docs/application/",
  "/docs/context/",
  "/docs/handling-requests/",
  "/docs/middleware/",
  "/docs/error-handling/",
  "/docs/api-reference/",
  "/docs/links/"
]
